use_frameworks!

target 'SimpleTableViewWrapper_Example' do
  pod 'SimpleTableViewWrapper', :path => '../'

  target 'SimpleTableViewWrapper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
