language: objective-c
osx_image: xcode9.2
branches:
  only:
    - master

cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
#   - pod install --project-directory=Example
script:
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SimpleTableViewWrapper.xcworkspace -scheme SimpleTableViewWrapper-Example -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
